###sign in
POST http://localhost:3000/users/signin
Content-Type: application/json

{
  "email": "subham.hero01@gmail.com",
  "password": "password"
}

### my profile

GET http://localhost:3000/users/me

###sign out
POST http://localhost:3000/users/logout

###test 
GET http://localhost:3000/orders/all
